services:
  ingress:
    image: peekaview/ingress:${DOCKER_TAG}
    command: run --config /etc/caddy.yaml --adapter yaml
    restart: unless-stopped
    environment:
      - API_DOMAIN=${API_DOMAIN}
    network_mode: "host"
    volumes:
      - ingress_data:/data

  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_PUBLIC_KEY=${LIVEKIT_PUBLIC_KEY}
    network_mode: "host"

  api:
    image: peekaview/api:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - VIDEO_SERVERS=${VIDEO_SERVERS}
      - CONTROL_SERVERS=${CONTROL_SERVERS}
    volumes:
      - api_storage:/storage
    ports:
      - "8080:80"
    networks:
      - internal

  controlserver:
    image: peekaview/controlserver:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal

  app:
    image: peekaview/app:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - internal

volumes:
  ingress_data:
  api_storage:
    # Optional: specify additional volume options here

networks:
  internal:
    driver: bridge
    name: peekaview
