version: '3.8'

services:

  caddy:
    image: peekaview/caddy
    restart: unless-stopped
    environment:
      - TURN_SERVER_DOMAIN=${TURN_SERVER_DOMAIN}
      - LIVEKIT_SERVER_DOMAIN=${LIVEKIT_SERVER_DOMAIN}
      - CONTROL_SERVER_DOMAIN=${CONTROL_SERVER_DOMAIN}
      - PEEKAVIEW_DOMAIN=${PEEKAVIEW_DOMAIN}
    network_mode: "host"
    volumes:
      - caddy_data:/data

  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_PUBLIC_KEY=${LIVEKIT_PUBLIC_KEY}
    network_mode: "host"

  api:
    image: peekaview/api
    restart: unless-stopped
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - VIDEO_SERVERS=${VIDEO_SERVERS}
      - CONTROL_SERVERS=${CONTROL_SERVERS}
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - internal

  controlserver:
    image: peekaview/controlserver
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - internal

  app:
    image: peekaview/app
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - internal

volumes:
  caddy_data:
    # Optional: specify additional volume options here

networks:
  internal:
    driver: bridge