#!/bin/sh

# Replace server name with environment variable
export SERVER_NAME=${API_DOMAIN}:80
export TURN_SHARED_SECRET=${TURN_SHARED_SECRET}
export JWT_SECRET=${JWT_SECRET}
export FIREBASE_API_KEY=${FIREBASE_API_KEY}
export FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
export FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
export FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
export FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
export FIREBASE_APP_ID=${FIREBASE_APP_ID}
export DEV_MODE=${DEV_MODE}

# Start FrankenPHP
exec frankenphp run --config /etc/caddy/Caddyfile 