name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
#    paths:
#      - 'app/**'

 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Set branch name
        id: set-branch
        run: |
          if [[ ${{ github.ref }} == refs/tags/latest ]]; then
            echo "branch=dev" >> $GITHUB_OUTPUT
          else
            echo "branch=dev" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        working-directory: ./app
        run: npm install
        
      - name: Build production
        working-directory: ./app
        run: npm run prod

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy app/build --project-name=peekaview --branch=${{ github.ref_name }}