name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'app/**'

 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Set branch name
        id: set-branch
        run: |
          if [[ ${{ github.ref }} == refs/tags/latest ]]; then
            echo "branch=dev" >> $GITHUB_OUTPUT
          else
            echo "branch=dev" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Setup Environment
        working-directory: ./app
        run: |
          npm install -g pnpm
          echo "VITE_APP_URL=https://develop.peekaview.de/" >> .env
          echo "VITE_API_URL=https://api.peekaview.de/" >> .env
          echo "VITE_CONNECT_SRC=https://*.peekaview.de wss://*.peekaview.de wss://c1.peekaview.de turns:t1.peekaview.de:443 turn:t1.peekaview.de:3478" >> .env
          echo "VITE_RTC_CONTROL_SERVER=wss://c1.peekaview.de/" >> .env
          echo "VITE_RTC_ICE_SERVER={ \"urls\": [\"turns:t1.peekaview.de:443\", \"turn:t1.peekaview.de:3478\"] }" >> .env
          
      - name: Install dependencies
        working-directory: ./app
        run: pnpm install
        
      - name: Build production
        working-directory: ./app
        run: pnpm run build

      - name: Add _headers file
        working-directory: ./app/out/renderer
        run: |
          echo "/*" > _headers
          echo "! X-Content-Type-Options" >> _headers
          echo "! X-Frame-Options" >> _headers
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy app/out/renderer --project-name=peekaview --branch=${{ github.ref_name }}