name: Release Electron App to Github Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "app/**"


jobs:
  create_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
    - uses: actions/checkout@v4    
      with:
        ref: ${{ github.ref }}  
        
    - name: Get Version
      id: get_version
      working-directory: ./app
      run: |
            VERSION=$(awk -F'"' '/"version"/ {print $4}' package.json)
            echo "Extracted version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create "v${{ steps.get_version.outputs.version }}" \
          --title "PeekaView v${{ steps.get_version.outputs.version }}" \
          --draft
  build_on_linux:
    if: ${{ false }}  # disable for now
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}

        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            version: 9
            run_install: false
    
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: 'app/'

        - name: Install Dependencies
          working-directory: ./app
          run: pnpm install            

        - name: Setup Environment
          working-directory: ./app
          run: |
            echo "VITE_APP_URL=https://develop.peekaview.de/" >> .env
            echo "VITE_API_URL=https://api.peekaview.de/" >> .env
            echo "VITE_CONNECT_SRC=https://*.peekaview.de wss://*.peekaview.de wss://c1.peekaview.de turns:t1.peekaview.de:443 turn:t1.peekaview.de:3478" >> .env
            echo "VITE_RTC_CONTROL_SERVER=wss://c1.peekaview.de/" >> .env
            echo "VITE_RTC_ICE_SERVER={ \"urls\": [\"turns:t1.peekaview.de:443\", \"turn:t1.peekaview.de:3478\"] }" >> .env

        - name: Build Electron App
          working-directory: ./app
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: pnpm run build:linux

  build_on_mac:
    needs: create_release
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}

        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            version: 9
            run_install: false
    
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: 'app/'

        - name: Install Dependencies
          working-directory: ./app
          run: pnpm install            

        - name: Setup Environment
          working-directory: ./app
          run: |
            echo "VITE_APP_URL=https://develop.peekaview.de/" >> .env
            echo "VITE_API_URL=https://api.peekaview.de/" >> .env
            echo "VITE_CONNECT_SRC=https://*.peekaview.de wss://*.peekaview.de wss://c1.peekaview.de turns:t1.peekaview.de:443 turn:t1.peekaview.de:3478" >> .env
            echo "VITE_RTC_CONTROL_SERVER=wss://c1.peekaview.de/" >> .env
            echo "VITE_RTC_ICE_SERVER={ \"urls\": [\"turns:t1.peekaview.de:443\", \"turn:t1.peekaview.de:3478\"] }" >> .env

        - name: Build Electron App
          working-directory: ./app
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
            CSC_LINK: ${{ secrets.CSC_LINK }}
            APPLEID: ${{ secrets.APPLEID }}
            APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
            TEAMID: ${{ secrets.TEAMID }}
            APPLE_ID: ${{ secrets.APPLEID }}
            APPLE_ID_PASSWORD: ${{ secrets.APPLEIDPASS }}
            APPLE_TEAM_ID: ${{ secrets.TEAMID }}
            APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
            DEBUG: electron-builder
          run: pnpm run build:mac

  build_on_win:
    if: ${{ false }}  # disable for now
    needs: create_release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
          with:
            ref: ${{ github.ref }}

        - uses: pnpm/action-setup@v4
          name: Install pnpm
          with:
            version: 9
            run_install: false
     
        - name: Install Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: 'app/'

        - name: Install Dependencies
          working-directory: ./app
          run: pnpm install            

        - name: Setup Environment
          working-directory: ./app
          run: |
             echo "VITE_APP_URL=https://develop.peekaview.de/" >> .env
             echo "VITE_API_URL=https://api.peekaview.de/" >> .env
             echo "VITE_CONNECT_SRC=https://*.peekaview.de wss://*.peekaview.de wss://c1.peekaview.de turns:t1.peekaview.de:443 turn:t1.peekaview.de:3478" >> .env
             echo "VITE_RTC_CONTROL_SERVER=wss://c1.peekaview.de/" >> .env
             echo "VITE_RTC_ICE_SERVER={ \"urls\": [\"turns:t1.peekaview.de:443\", \"turn:t1.peekaview.de:3478\"] }" >> .env

        - name: Build Electron App
          working-directory: ./app
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: pnpm run build:win